### ISSUE TITLE
How to use the model to generate recommendations?

### ISSUE THREAD

**Issue by lucaspk** [xue-pai/FinalMLP#1]
Hi, there.

First, thank you very much for the great implementation of this model.

I'm new to this universe of CTR-related problems like the one that's addressed by this FinalMLP model.

I was wondering if it's possible to generate recommendations by using the output of this model. 

For example, if this model is capable of generating the most likely products some users would click on, then we can recommend these products to them.

Is it possible to achieve that with this model? If so, would you mind pointing me in the direction of generating the output that's convenient to be used in a production setup?

Thank you very much in advance.

**Comment by zhujiem** [comment]
Recently, we perform a similar competition task, with detailed steps on data preprocessing, model training, and model prediction. You can use it as a reference. https://github.com/xue-pai/Baidu2023_CVR_Challenge
